### ISSUE TITLE
Clean up README.md file

### ISSUE THREAD

**Issue by jenlampton** [backdrop-contrib/insert_view#1]
The README.md file for this project is not properly formatted.  Sometimes this can happen when projects are ported over from Drupal, since there wasn't a lot of direction on formatting of Drupal's README.txt files.  Please refer to our [contributor guidelines](https://github.com/backdrop-ops/contrib) for an [example README.md file](https://raw.githubusercontent.com/backdrop-ops/contrib/master/examples/README.md) that you can copy. 

The main problem is the HTML formatting which needs to be removed. Markdown files (ending in .md) have [their own formatting](https://help.github.com/articles/markdown-basics) similar to what we use here on GitHub :)

It is especially important to keep the readme files clean for Backdrop projects since that is what is used for the project page on backdropcms.org.  Take a look at the page for this project to see the problem: https://backdropcms.org/project/insert_view

**Comment by vtad** [comment]
Hi,
There is no HTML Code in the git Version or in the download Version of 
README.md.
  I don't know how it gets into the Backdrop Documentation page of this 
module.

Am 21.09.2015 um 21:41 schrieb Jen Lampton:

**Comment by jenlampton** [comment]
Yes, you are right.  Something changed on backdropcms.org recently that was causing all the HTML formatting to appear.  I believe we've fixed it now, sorry about the trouble (and for the false issue).  Thank  you for contributing this module for Backdrop :)
